// Generated by tools/generate_tier0.py. Do not edit manually.
`default_nettype none

module tenon_ics55_qfn32_no_pll_fillers ();
  (* keep = "true" *) PFILL50 u_south_leading_0 ();
  (* keep = "true" *) PFILL20 u_south_leading_1 ();
  (* keep = "true" *) PFILL20 u_south_leading_2 ();
  (* keep = "true" *) PFILL2 u_south_leading_3 ();
  (* keep = "true" *) PFILL50 u_south_trailing_0 ();
  (* keep = "true" *) PFILL20 u_south_trailing_1 ();
  (* keep = "true" *) PFILL20 u_south_trailing_2 ();
  (* keep = "true" *) PFILL2 u_south_trailing_3 ();
  (* keep = "true" *) PFILL50 u_east_leading_0 ();
  (* keep = "true" *) PFILL20 u_east_leading_1 ();
  (* keep = "true" *) PFILL10 u_east_leading_2 ();
  (* keep = "true" *) PFILL5 u_east_leading_3 ();
  (* keep = "true" *) PFILL2 u_east_leading_4 ();
  (* keep = "true" *) PFILL2 u_east_leading_5 ();
  (* keep = "true" *) PFILL50 u_east_trailing_0 ();
  (* keep = "true" *) PFILL20 u_east_trailing_1 ();
  (* keep = "true" *) PFILL20 u_east_trailing_2 ();
  (* keep = "true" *) PFILL50 u_north_leading_0 ();
  (* keep = "true" *) PFILL20 u_north_leading_1 ();
  (* keep = "true" *) PFILL20 u_north_leading_2 ();
  (* keep = "true" *) PFILL2 u_north_leading_3 ();
  (* keep = "true" *) PFILL50 u_north_trailing_0 ();
  (* keep = "true" *) PFILL20 u_north_trailing_1 ();
  (* keep = "true" *) PFILL20 u_north_trailing_2 ();
  (* keep = "true" *) PFILL2 u_north_trailing_3 ();
  (* keep = "true" *) PFILL50 u_west_leading_0 ();
  (* keep = "true" *) PFILL20 u_west_leading_1 ();
  (* keep = "true" *) PFILL10 u_west_leading_2 ();
  (* keep = "true" *) PFILL5 u_west_leading_3 ();
  (* keep = "true" *) PFILL2 u_west_leading_4 ();
  (* keep = "true" *) PFILL2 u_west_leading_5 ();
  (* keep = "true" *) PFILL50 u_west_trailing_0 ();
  (* keep = "true" *) PFILL20 u_west_trailing_1 ();
  (* keep = "true" *) PFILL20 u_west_trailing_2 ();
endmodule

`default_nettype wire
