#!/usr/bin/env python3
"""Generate GF180 OCD IO leaf-instance placement overrides."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from generate_tier0 import (
    POWER_INSTANCE_PREFIX,
    ROOT,
    SIDES,
    SPEC_PATH,
    build_records,
    pad_path,
    yaml_list,
)


OUTPUT_DIR = ROOT / "flow" / "gf180"


def gf180_pad_path(record: dict) -> str:
    """Return the physical GF180 PadCell instance beneath its helper wrapper."""
    instance = record["instance"]
    if record["function"] not in POWER_INSTANCE_PREFIX:
        instance = f"{instance}.u_pad"
    return pad_path(instance)


def render_profile(spec: dict, profile: dict) -> str:
    records = build_records(spec, profile)
    placement_blocks = []
    for side in SIDES:
        selected = [record for record in records if record["side"] == side]
        if side in {"north", "west"}:
            selected.reverse()
        placement_blocks.append(yaml_list(f"PAD_{side.upper()}", [gf180_pad_path(record) for record in selected]))

    return """# Generated by tools/generate_gf180_placement.py. Do not edit manually.
meta:
  version: 3
  flow: Chip

""" + "\n\n".join(placement_blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files differ")
    args = parser.parse_args()

    spec = json.loads(SPEC_PATH.read_text())
    mismatches: list[Path] = []
    for profile in spec["profiles"]:
        path = OUTPUT_DIR / f"{profile['id']}_placement.yaml"
        content = render_profile(spec, profile)
        if args.check:
            if not path.exists() or path.read_text() != content:
                mismatches.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if mismatches:
        print("Generated files are stale:", *mismatches, sep="\n  ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
